with rows as (
INSERT INTO $DATABASE_SCHEMA.ADDRESSES (HOUSE_NUMBER, PLOT_NUMBER, STREET) VALUES ('1', '0', 'Покровская') RETURNING id as address_id
)
INSERT INTO $DATABASE_SCHEMA.USERS (ADDRESS_ID, USER_NAME, PASSWORD, ROLES, FIRST_NAME, LAST_NAME) 
SELECT address_id, 'admin@baltsloboda2.ru', '$2a$10$Y9iceFh92PKUK5d2alIgzOeSy.Gg6kX6/o.Cn32ARH2H9whZaZ17K', 'ROLE_ADMIN', 'Admin', 'Admin'
FROM rows;

with rows as (
INSERT INTO $DATABASE_SCHEMA.ADDRESSES (HOUSE_NUMBER, PLOT_NUMBER, STREET) VALUES ('34', '172', 'Солнечная') RETURNING id as address_id
)
INSERT INTO $DATABASE_SCHEMA.USERS (ADDRESS_ID, USER_NAME, PASSWORD, ROLES, FIRST_NAME, LAST_NAME) 
SELECT address_id, 'olshanskyev@gmail.com', '$2a$10$ofyHZ3LvIfDv.ZFgA0xm/uBe7IEgmtKcid5KslnGUmDuI1rP5cRXW', 'ROLE_USER', 'Ольшанский', 'Евгений'
FROM rows;
